# Generated by Django 5.0.2 on 2024-02-29 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=10, verbose_name='Ячейка хранения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apteka.product', verbose_name='Товар')),
            ],
        ),
    ]
