# Generated by Django 5.0.2 on 2024-03-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apteka', '0003_product_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sklad',
            name='name_sklad',
            field=models.CharField(default=' ', max_length=100, verbose_name='Имя скалада'),
        ),
    ]
